name: math_alarm_app_new
description: Una aplicación de alarma que requiere resolver problemas matemáticos para apagarla.

publish_to: 'none' # Evita publicar en pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  # UI
  cupertino_icons: ^1.0.6
  
  # Estado
  provider: ^6.1.1
  
  # Almacenamiento local
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  
  # Notificaciones y alarmas
  flutter_local_notifications: ^19.1.0
  audioplayers: ^6.4.0
  vibration: ^1.7.7
  
  # Utilidades
  intl: ^0.20.2
  timezone: ^0.10.1
  permission_handler: ^12.0.0+1
  file_picker: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  mockito: ^5.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/images/